name: Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11.0.14+9'
    - uses: subosito/flutter-action@v2
      with:
          flutter-version: '2.10.5'
          
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release
